import { StyleSheet } from "react-native";

export default StyleSheet.create({
  containerGradient: {
    flex: 1,
  },
  backButton: {
    marginTop: 50,
    marginLeft: 16,
    backgroundColor: "#1e293b",
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  headerContainer: {
    marginTop: 20,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  title: {
    color: "#f1f5f9",
    fontSize: 24,
    fontWeight: "700",
  },
  subtitle: {
    color: "#cbd5e1",
    fontSize: 14,
    marginTop: 4,
  },
  produtoContainer: {
    backgroundColor: "#1e293b",
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  produtoNome: {
    color: "#f1f5f9",
    fontSize: 20,
    fontWeight: "600",
    marginBottom: 8,
  },
  produtoImagem: {
    width: "100%",
    height: 180,
    borderRadius: 12,
    marginBottom: 12,
  },
  ingredientesTitle: {
    color: "#94a3b8",
    fontWeight: "600",
    fontSize: 16,
    marginBottom: 10,
  },
  ingredienteItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#273449",
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
  },
  ingredienteSelected: {
    backgroundColor: "#22c55e",
  },
  ingredienteImagem: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 12,
  },
  ingredienteInfo: {
    flex: 1,
  },
  ingredienteNome: {
    color: "#f1f5f9",
    fontSize: 16,
    fontWeight: "600",
  },
  ingredientePreco: {
    color: "#a5b4fc",
    fontSize: 14,
    marginTop: 2,
  },
  checkboxCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "#94a3b8",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: "#22c55e",
    borderColor: "#22c55e",
  },
  checkboxInnerCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "white",
  },
  quantidadeContainer: {
    backgroundColor: "#334155",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  quantidadeText: {
    color: "#f1f5f9",
    fontWeight: "600",
  },
  button: {
    backgroundColor: "#22c55e",
    marginHorizontal: 16,
    borderRadius: 12,
    paddingVertical: 16,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    left: 16,
    right: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  buttonText: {
    color: "#f1f5f9",
    fontWeight: "700",
    fontSize: 18,
  },
});
